### ISSUE TITLE
All hotspots move to the top left corner

### ISSUE THREAD

**Issue by msperli** [MaxBazarov/demo-station-plugin#2]
I have a simple test page with a few hotspot, but all the hotspots move to the top left corner of the frame. 
I am using auto layout but that doesn't seem to affect  it.

The hotspots were attached to the image and the first tan box.
<img width="252" alt="Screen Shot 2021-11-16 at 11 02 49 AM" src="https://user-images.githubusercontent.com/71150828/142021558-00468978-5828-4045-83b4-e2abab00654c.png">

I also put each element inside of a component for the auto layout
<img width="796" alt="image" src="https://user-images.githubusercontent.com/71150828/142021883-73ab8a24-c9b1-4b8e-a64e-8a6c06522b0e.png">

**Comment by MaxBazarov** [comment]
Got it

**Comment by MaxBazarov** [comment]
@msperli  I just published the fixed version. Please validate it.

**Comment by MaxBazarov** [comment]
@msperli  Does it work fine now?

**Comment by msperli** [comment]
Fixed. Great, thanks!
